# Environment
MKDIR=mkdir
CP=cp
CCADMIN=CCadmin
RANLIB=ranlib

# build
build: .build-post
.build-pre:
.build-post: .build-impl

# clean
clean: .clean-post
.clean-pre:
.clean-post: .clean-impl

# clobber
clobber: .clobber-post
.clobber-pre:
.clobber-post: .clobber-impl

# all
all: .all-post
.all-pre:
.all-post: .all-impl

# help
help: .help-post
.help-pre:
.help-post: .help-impl

# Include project implementation makefile
include nbproject/Makefile-impl.mk

# Include project make variables
include nbproject/Makefile-variables.mk
