#define DELAY delay(200)
#define DELAY_SHORT delay(100)
#define DELAY_LONG delay(1000)
static byte gear = 7;

// send "BEEFCAkE" accross the seven segments
#ifdef TROLL_STARTUP
void startupSequence() {

	//Flashing LEDs here!

	//GOING UP!
	displays.setRow(0,0,0x80);
	displays.setRow(0,1,0x80);
	displays.setRow(0,2,0x80);
	displays.setRow(0,3,0x80);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setRow(1,4,SEV_SEG_B);
	changeGear();
	DELAY;
	displays.setRow(0,0,0x80);
	displays.setRow(0,1,0x80);
	displays.setRow(0,2,0x80);
	displays.setRow(0,3,0x80);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setRow(1,5,SEV_SEG_B);
	displays.setChar(1,4,'E',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xC0);
	displays.setRow(0,1,0xC0);
	displays.setRow(0,2,0xC0);
	displays.setRow(0,3,0xC0);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setRow(1,6,SEV_SEG_B);
	displays.setChar(1,5,'E',false);
	displays.setChar(1,4,'E',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xC0);
	displays.setRow(0,1,0xC0);
	displays.setRow(0,2,0xC0);
	displays.setRow(0,3,0xC0);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setRow(1,7,SEV_SEG_B);
	displays.setChar(1,6,'E',false);
	displays.setChar(1,5,'E',false);
	displays.setChar(1,4,'F',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xE0);
	displays.setRow(0,1,0xE0);
	displays.setRow(0,2,0xE0);
	displays.setRow(0,3,0xE0);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setRow(1,0,SEV_SEG_B);
	displays.setChar(1,7,'E',false);
	displays.setChar(1,6,'E',false);
	displays.setChar(1,5,'F',false);
	displays.setRow(1,4,SEV_SEG_C);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xE0);
	displays.setRow(0,1,0xE0);
	displays.setRow(0,2,0xE0);
	displays.setRow(0,3,0xE0);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setRow(1,1,SEV_SEG_B);
	displays.setChar(1,0,'E',false);
	displays.setChar(1,7,'E',false);
	displays.setChar(1,6,'F',false);
	displays.setRow(1,5,SEV_SEG_C);
	displays.setChar(1,4,'A',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xF0);
	displays.setRow(0,1,0xF0);
	displays.setRow(0,2,0xF0);
	displays.setRow(0,3,0xF0);
	displays.setChar(1,3,' ',false);
	displays.setRow(1,2,SEV_SEG_B);
	displays.setChar(1,1,'E',false);
	displays.setChar(1,0,'E',false);
	displays.setChar(1,7,'F',false);
	displays.setRow(1,6,SEV_SEG_C);
	displays.setChar(1,5,'A',false);
	displays.setRow(1,4,SEV_SEG_k);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xF0);
	displays.setRow(0,1,0xF0);
	displays.setRow(0,2,0xF0);
	displays.setRow(0,3,0xF0);
	displays.setRow(1,3,SEV_SEG_B);
	displays.setChar(1,2,'E',false);
	displays.setChar(1,1,'E',false);
	displays.setChar(1,0,'F',false);
	displays.setRow(1,7,SEV_SEG_C);
	displays.setChar(1,6,'A',false);
	displays.setRow(1,5,SEV_SEG_k);
	displays.setChar(1,4,'E',false);
	changeGear();
	DELAY;

	//////////////////////////
	// GOING DOWN!          //
	//////////////////////////

	displays.setRow(0,0,0xF8);
	displays.setRow(0,1,0xF8);
	displays.setRow(0,2,0xF8);
	displays.setRow(0,3,0xF8);
	displays.setChar(1,3,'E',false);
	displays.setChar(1,2,'E',false);
	displays.setChar(1,1,'F',false);
	displays.setRow(1,0,SEV_SEG_C);
	displays.setChar(1,7,'A',false);
	displays.setRow(1,6,SEV_SEG_k);
	displays.setChar(1,5,'E',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xF8);
	displays.setRow(0,1,0xF8);
	displays.setRow(0,2,0xF8);
	displays.setRow(0,3,0xF8);
	displays.setChar(1,3,'E',false);
	displays.setChar(1,2,'F',false);
	displays.setRow(1,1,SEV_SEG_C);
	displays.setChar(1,0,'A',false);
	displays.setRow(1,7,SEV_SEG_k);
	displays.setChar(1,6,'E',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFC);
	displays.setRow(0,1,0xFC);
	displays.setRow(0,2,0xFC);
	displays.setRow(0,3,0xFC);
	displays.setChar(1,3,'F',false);
	displays.setRow(1,2,SEV_SEG_C);
	displays.setChar(1,1,'A',false);
	displays.setRow(1,0,SEV_SEG_k);
	displays.setChar(1,7,'E',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFC);
	displays.setRow(0,1,0xFC);
	displays.setRow(0,2,0xFC);
	displays.setRow(0,3,0xFC);
	displays.setRow(1,3,SEV_SEG_C);
	displays.setChar(1,2,'A',false);
	displays.setRow(1,1,SEV_SEG_k);
	displays.setChar(1,0,'E',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFE);
	displays.setRow(0,1,0xFE);
	displays.setRow(0,2,0xFE);
	displays.setRow(0,3,0xFE);
	displays.setChar(1,3,'A',false);
	displays.setRow(1,2,SEV_SEG_k);
	displays.setChar(1,1,'E',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFE);
	displays.setRow(0,1,0xFE);
	displays.setRow(0,2,0xFE);
	displays.setRow(0,3,0xFE);
	displays.setRow(1,3,SEV_SEG_k);
	displays.setChar(1,2,'E',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setChar(1,3,'E',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);

  // Flash PEtE 3 times!
	for(byte i = 0; i < 4; i++) {
		gear = -1;
		changeGear();
		displays.setRow(0,0,0xFF);
		displays.setRow(0,1,0xFF);
		displays.setRow(0,2,0xFF);
		displays.setRow(0,3,0xFF);
		displays.setRow(0,4,0xC0);
		displays.setChar(1,3,'P',false);
		displays.setChar(1,2,'E',false);
		displays.setRow(1, 1, SEV_SEG_t);
		displays.setChar(1,0,'E',false);
		displays.setChar(1,7,'P',false);
		displays.setChar(1,6,'E',false);
		displays.setRow(1, 5, SEV_SEG_t);
		displays.setChar(1,4,'E',false);
		DELAY_SHORT;
		clearGear();
		displays.clearDisplay(0);
		displays.clearDisplay(1);
		DELAY_SHORT;
	}

	// turn on everything briefly
	gear = -1;
	changeGear();
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0xC0);
	displays.setDigit(1, 0, 0x08, true);
	displays.setDigit(1, 1, 0x08, true);
	displays.setDigit(1, 2, 0x08, true);
	displays.setDigit(1, 3, 0x08, true);
	displays.setDigit(1, 4, 0x08, true);
	displays.setDigit(1, 5, 0x08, true);
	displays.setDigit(1, 6, 0x08, true);
	displays.setDigit(1, 7, 0x08, true);
	DELAY_LONG;

	// clear displays
	clearGear();
	displays.clearDisplay(0);
	displays.clearDisplay(1);
}
#else

// send "7H15 15 1LL" accross the seven segments
void startupSequence() {

	//Flashing LEDs here!

	//GOING UP!
	displays.setRow(0,0,0x80);
	displays.setRow(0,1,0x80);
	displays.setRow(0,2,0x80);
	displays.setRow(0,3,0x80);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setDigit(1,4,7,false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0x80);
	displays.setRow(0,1,0x80);
	displays.setRow(0,2,0x80);
	displays.setRow(0,3,0x80);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setDigit(1,5,7,false);
	displays.setChar(1,4,'H',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xC0);
	displays.setRow(0,1,0xC0);
	displays.setRow(0,2,0xC0);
	displays.setRow(0,3,0xC0);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setDigit(1,6,7,false);
	displays.setChar(1,5,'H',false);
	displays.setDigit(1,4,1,false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xC0);
	displays.setRow(0,1,0xC0);
	displays.setRow(0,2,0xC0);
	displays.setRow(0,3,0xC0);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setDigit(1,7,7,false);
	displays.setChar(1,6,'H',false);
	displays.setDigit(1,5,1,false);
	displays.setDigit(1,4,5,false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xE0);
	displays.setRow(0,1,0xE0);
	displays.setRow(0,2,0xE0);
	displays.setRow(0,3,0xE0);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setDigit(1,0,7,false);
	displays.setChar(1,7,'H',false);
	displays.setDigit(1,6,1,false);
	displays.setDigit(1,5,5,false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xE0);
	displays.setRow(0,1,0xE0);
	displays.setRow(0,2,0xE0);
	displays.setRow(0,3,0xE0);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setDigit(1,1,7,false);
	displays.setChar(1,0,'H',false);
	displays.setDigit(1,7,1,false);
	displays.setDigit(1,6,5,false);
	displays.setChar(1,5,' ',false);
	displays.setDigit(1,4,1,false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xF0);
	displays.setRow(0,1,0xF0);
	displays.setRow(0,2,0xF0);
	displays.setRow(0,3,0xF0);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setDigit(1,2,7,false);
	displays.setChar(1,1,'H',false);
	displays.setDigit(1,0,1,false);
	displays.setDigit(1,7,5,false);
	displays.setChar(1,6,' ',false);
	displays.setDigit(1,5,1,false);
	displays.setDigit(1,4,5,false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xF0);
	displays.setRow(0,1,0xF0);
	displays.setRow(0,2,0xF0);
	displays.setRow(0,3,0xF0);
	displays.setRow(0,4,0x00);
	displays.setDigit(1,3,7,false);
	displays.setChar(1,2,'H',false);
	displays.setDigit(1,1,1,false);
	displays.setDigit(1,0,5,false);
	displays.setChar(1,7,' ',false);
	displays.setDigit(1,6,1,false);
	displays.setDigit(1,5,5,false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;


	//////////////////////////
	// GOING DOWN!          //
	//////////////////////////

	displays.setRow(0,0,0xF8);
	displays.setRow(0,1,0xF8);
	displays.setRow(0,2,0xF8);
	displays.setRow(0,3,0xF8);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,'H',false);
	displays.setDigit(1,2,1,false);
	displays.setDigit(1,1,5,false);
	displays.setChar(1,0,' ',false);
	displays.setDigit(1,7,1,false);
	displays.setDigit(1,6,5,false);
	displays.setChar(1,5,' ',false);
	displays.setDigit(1,4,1,false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xF8);
	displays.setRow(0,1,0xF8);
	displays.setRow(0,2,0xF8);
	displays.setRow(0,3,0xF8);
	displays.setRow(0,4,0x00);
	displays.setDigit(1,3,1,false);
	displays.setDigit(1,2,5,false);
	displays.setChar(1,1,' ',false);
	displays.setDigit(1,0,1,false);
	displays.setDigit(1,7,5,false);
	displays.setChar(1,6,' ',false);
	displays.setDigit(1,5,1,false);
	displays.setChar(1,4,'L',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFC);
	displays.setRow(0,1,0xFC);
	displays.setRow(0,2,0xFC);
	displays.setRow(0,3,0xFC);
	displays.setRow(0,4,0x00);
	displays.setDigit(1,3,5,false);
	displays.setChar(1,2,' ',false);
	displays.setDigit(1,1,1,false);
	displays.setDigit(1,0,5,false);
	displays.setChar(1,7,' ',false);
	displays.setDigit(1,6,1,false);
	displays.setChar(1,5,'L',false);
	displays.setChar(1,4,'L',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFC);
	displays.setRow(0,1,0xFC);
	displays.setRow(0,2,0xFC);
	displays.setRow(0,3,0xFC);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setDigit(1,2,1,false);
	displays.setDigit(1,1,5,false);
	displays.setChar(1,0,' ',false);
	displays.setDigit(1,7,1,false);
	displays.setChar(1,6,'L',false);
	displays.setChar(1,5,'L',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFE);
	displays.setRow(0,1,0xFE);
	displays.setRow(0,2,0xFE);
	displays.setRow(0,3,0xFE);
	displays.setRow(0,4,0x00);
	displays.setDigit(1,3,1,false);
	displays.setDigit(1,2,5,false);
	displays.setChar(1,1,' ',false);
	displays.setDigit(1,0,1,false);
	displays.setChar(1,7,'L',false);
	displays.setChar(1,6,'L',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFE);
	displays.setRow(0,1,0xFE);
	displays.setRow(0,2,0xFE);
	displays.setRow(0,3,0xFE);
	displays.setRow(0,4,0x00);
	displays.setDigit(1,3,5,false);
	displays.setChar(1,2,' ',false);
	displays.setDigit(1,1,1,false);
	displays.setChar(1,0,'L',false);
	displays.setChar(1,7,'L',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0x00);
	displays.setChar(1,3,' ',false);
	displays.setDigit(1,2,1,false);
	displays.setChar(1,1,'L',false);
	displays.setChar(1,0,'L',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0x00);
	displays.setDigit(1,3,1,false);
	displays.setChar(1,2,'L',false);
	displays.setChar(1,1,'L',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0x80);
	displays.setChar(1,3,'L',false);
	displays.setChar(1,2,'L',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0x80);
	displays.setChar(1,3,'L',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);
	changeGear();
	DELAY;
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0xC0);
	displays.setChar(1,3,' ',false);
	displays.setChar(1,2,' ',false);
	displays.setChar(1,1,' ',false);
	displays.setChar(1,0,' ',false);
	displays.setChar(1,7,' ',false);
	displays.setChar(1,6,' ',false);
	displays.setChar(1,5,' ',false);
	displays.setChar(1,4,' ',false);

	// Flash everything 3 times!
	for(byte i = 0; i < 4; i++) {
		gear = -1;
		changeGear();
		displays.setRow(0,0,0xFF);
		displays.setRow(0,1,0xFF);
		displays.setRow(0,2,0xFF);
		displays.setRow(0,3,0xFF);
		displays.setRow(0,4,0xC0);
		displays.setDigit(1, 0, 0x08, true);
		displays.setDigit(1, 1, 0x08, true);
		displays.setDigit(1, 2, 0x08, true);
		displays.setDigit(1, 3, 0x08, true);
		displays.setDigit(1, 4, 0x08, true);
		displays.setDigit(1, 5, 0x08, true);
		displays.setDigit(1, 6, 0x08, true);
		displays.setDigit(1, 7, 0x08, true);
		DELAY_SHORT;
		clearGear();
		displays.clearDisplay(0);
		displays.clearDisplay(1);
		DELAY_SHORT;
	}

	// turn on everything briefly and display "1LL1NO15"
	displays.setRow(0,0,0xFF);
	displays.setRow(0,1,0xFF);
	displays.setRow(0,2,0xFF);
	displays.setRow(0,3,0xFF);
	displays.setRow(0,4,0xC0);
	displays.setDigit(1,3,1,false);
	displays.setChar(1,2,'L',false);
	displays.setChar(1,1,'L',false);
	displays.setDigit(1,0,1,false);
	displays.setRow(1, 7, SEV_SEG_N);
	displays.setDigit(1,6,0,false);
	displays.setDigit(1,5,1,false);
	displays.setDigit(1,4,5,false);
	DELAY_LONG;

	// clear displays
	clearGear();
	displays.clearDisplay(0);
	displays.clearDisplay(1);

	// reset gear
	gear = 7;
}
#endif

// function to cycle through the gears
void changeGear() {
	// cycle gears
	if(++gear > 6)
		gear = 0;

	digitalWriteFast(ALPHA_LAT_PIN, LOW);
	shiftOut(ALPHA_DATA_PIN, ALPHA_CLK_PIN, MSBFIRST, gearArray[gear]);
	digitalWriteFast(ALPHA_LAT_PIN, HIGH);
}

// function to clear the alphanumeric display
void clearGear() {
	digitalWriteFast(ALPHA_LAT_PIN, LOW);
	shiftOut(ALPHA_DATA_PIN, ALPHA_CLK_PIN, MSBFIRST, ALPHA_NULL);
	digitalWriteFast(ALPHA_LAT_PIN, HIGH);
}
