######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 7 19:46:14 2014
######################################################################

CONFIG += serialport
QT += widgets
QT += serialport
TEMPLATE = app

DEPENDPATH += . Telemetry_Monitor
INCLUDEPATH += .

# Input
HEADERS += display.h \
           data.h \
           config.h
SOURCES += display.cpp \
           main.cpp \
           data.cpp
